# Generated by Django 4.2.3 on 2023-08-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("realtorapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="picture",
            field=models.FileField(blank=True, null=True, upload_to="media"),
        ),
        migrations.CreateModel(
            name="product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "Description",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("nasrcity", "nasrcity"),
                            ("madity", "madity"),
                            ("elshrouk", "elshrouk"),
                            ("Giza", "Giza"),
                            ("The Fifth Settlement", "The Fifth Settlement"),
                            ("badr", "badr"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "type_house",
                    models.TextField(
                        blank=True,
                        choices=[
                            ("Houses", "Houses"),
                            ("Appartment", "Appartment"),
                            ("Townhell", "Townhell"),
                            ("Vacation", "Vacation"),
                        ],
                        null=True,
                    ),
                ),
                (
                    "style_house",
                    models.TextField(
                        blank=True,
                        choices=[("A-Frame", "A-Frame"), ("Spanish", "Spanish")],
                        null=True,
                    ),
                ),
                ("area", models.FloatField(blank=True, null=True)),
                ("price", models.FloatField(blank=True, null=True)),
                ("number_kitchen", models.IntegerField(blank=True, null=True)),
                ("number_bedroom", models.IntegerField(blank=True, null=True)),
                ("number_bathroom", models.IntegerField(blank=True, null=True)),
                ("pics", models.FileField(null=True, upload_to="media")),
                (
                    "profile_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="realtorapp.profile",
                    ),
                ),
            ],
        ),
    ]
