# Generated by Django 4.2.3 on 2023-08-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtorapp", "0002_alter_profile_picture_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
