# Generated by Django 4.2.3 on 2023-08-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtorapp", "0005_produc_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produc_images",
            name="img",
            field=models.FileField(null=True, upload_to="media/house-picture"),
        ),
    ]
