# Generated by Django 4.2.3 on 2023-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("realtorapp", "0006_alter_produc_images_img"),
    ]

    operations = [
        migrations.CreateModel(
            name="messageQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("qustion", models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="produc_images",
            name="img",
            field=models.FileField(null=True, upload_to="media"),
        ),
    ]
