# Generated by Django 4.2.4 on 2023-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0009_remove_saved_message_reciver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_message',
            name='time_stamp',
            field=models.DateTimeField(),
        ),
    ]
