# Generated by Django 4.2.4 on 2023-09-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0010_alter_saved_message_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_message',
            name='time_stamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
