# Generated by Django 4.2.4 on 2023-09-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realtorapp', '0012_profile_status_alter_saved_message_reciver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(default='offline', max_length=10),
        ),
    ]
